### ISSUE TITLE
unification of Help menu

### ISSUE THREAD

**Issue by kinichiro** [kinichiro/kicad-doc#1]
KiCad Help menu should be unified.
- library editor
  - "Contents" -> "Eeschema Manual"
- cvpcb
  - add "Getting Started in KiCad"
- pcbnew
  - "Contents" -> "PcbNew Manual"
- gerbview
  - "Contents" -> "GerbView Manual"
  - add "Getting Started in KiCad"
  - fix invalid 2 icons
- pl_editor
  - "Contents" -> "Page Layout Editor Manual"
  - fix invalid 2 icons

I put the fixing image below.
![help](https://cloud.githubusercontent.com/assets/4927823/10050075/728fc9b8-6255-11e5-90cd-16dddd7d7a88.png)

**Comment by nickoe** [comment]
This is fixed upstream isn't it?

**Comment by kinichiro** [comment]
Yes, I forgot to close this. thanks.
